"""Block 2 — Neural lap-time map ``T_lap(deploy, mass, initial SoC)``.

A small multilayer perceptron is **fitted to laps generated by the plant**. It is
a fitted surrogate over a declared parameter range, not a measured pace model and
not a reproduction of any team's map. Outside its training range it returns an
out-of-domain flag rather than extrapolating.

The network is deliberately tiny: a few dozen parameters trained on a few
hundred simulated laps. That is enough to be a smooth, differentiable lap-time
map, and it is honest about its data.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field, replace

import numpy as np

from ..contracts.state import (
    ActionFamily,
    BatteryParams,
    Control,
    Track,
    VehicleParams,
    cornering_speed_limit_mps,
)
from ..simulation.plant import Plant, initial_state
from ..simulation.tyres import TyreParams


@dataclass
class LapSample:
    deploy_w: float
    mass_kg: float
    soc0: float
    lap_time_s: float


def simulate_lap(
    track: Track,
    vehicle: VehicleParams,
    battery: BatteryParams,
    deploy_w: float,
    mass_kg: float,
    soc0: float,
    tyre_params: TyreParams | None = None,
    target_ceiling_mps: float = 92.0,
    dt_s: float = 0.05,
    max_steps: int = 6000,
) -> float:
    """Run one lap on the plant at a fixed deployment and return elapsed time."""
    lap_vehicle = replace(vehicle, mass_kg=mass_kg) if mass_kg != vehicle.mass_kg else vehicle
    plant = Plant(lap_vehicle, battery, track, tyre_params)
    state = initial_state(battery, progress_m=0.0, speed_mps=80.0)
    state.battery.soc = soc0
    elapsed = 0.0
    for _ in range(max_steps):
        limit = cornering_speed_limit_mps(state.progress_m, track, lap_vehicle, mass_kg)
        control = Control(
            ActionFamily.REFERENCE, deploy_w, min(target_ceiling_mps, limit), dt_s
        )
        step = plant.step(state, control, dt_s)
        state = step.state
        elapsed += dt_s
        if state.progress_m >= track.length_m:
            return elapsed
    return float("nan")


def generate_dataset(
    track: Track,
    vehicle: VehicleParams,
    battery: BatteryParams,
    n_samples: int = 240,
    tyre_params: TyreParams | None = None,
    seed: int = 0,
    deploy_range_w: tuple[float, float] = (0.0, 250_000.0),
    mass_range_kg: tuple[float, float] = (740.0, 860.0),
    soc_range: tuple[float, float] = (0.35, 0.90),
) -> list[LapSample]:
    rng = random.Random(seed)
    samples: list[LapSample] = []
    for _ in range(n_samples):
        deploy = rng.uniform(*deploy_range_w)
        mass = rng.uniform(*mass_range_kg)
        soc0 = rng.uniform(*soc_range)
        lap_time = simulate_lap(
            track, vehicle, battery, deploy, mass, soc0, tyre_params
        )
        if np.isfinite(lap_time):
            samples.append(LapSample(deploy, mass, soc0, lap_time))
    return samples


@dataclass
class NeuralLapTimeMap:
    """Small MLP fitted to simulated laps."""

    hidden: int = 24
    seed: int = 0
    epochs: int = 900
    learning_rate: float = 0.01
    grad_clip: float = 1.0
    _w1: np.ndarray = field(default=None, init=False, repr=False)
    _b1: np.ndarray = field(default=None, init=False, repr=False)
    _w2: np.ndarray = field(default=None, init=False, repr=False)
    _b2: float = field(default=0.0, init=False, repr=False)
    _x_mean: np.ndarray = field(default=None, init=False, repr=False)
    _x_std: np.ndarray = field(default=None, init=False, repr=False)
    _y_mean: float = field(default=0.0, init=False, repr=False)
    _y_std: float = field(default=1.0, init=False, repr=False)
    _x_min: np.ndarray = field(default=None, init=False, repr=False)
    _x_max: np.ndarray = field(default=None, init=False, repr=False)
    train_rmse_s: float = field(default=float("nan"), init=False)
    n_train: int = field(default=0, init=False)

    def fit(self, samples: list[LapSample]) -> "NeuralLapTimeMap":
        if len(samples) < 10:
            raise ValueError("need at least 10 samples to fit")
        rng = np.random.default_rng(self.seed)
        X = np.array([[s.deploy_w, s.mass_kg, s.soc0] for s in samples])
        y = np.array([s.lap_time_s for s in samples])
        self._x_mean, self._x_std = X.mean(axis=0), X.std(axis=0) + 1e-9
        self._x_min, self._x_max = X.min(axis=0), X.max(axis=0)
        self._y_mean, self._y_std = float(y.mean()), float(y.std() + 1e-9)
        Xn = (X - self._x_mean) / self._x_std
        yn = (y - self._y_mean) / self._y_std

        self._w1 = rng.normal(0.0, 0.5, size=(3, self.hidden))
        self._b1 = np.zeros(self.hidden)
        self._w2 = rng.normal(0.0, 0.5, size=self.hidden)
        self._b2 = 0.0

        for _ in range(self.epochs):
            with np.errstate(over="ignore", invalid="ignore", divide="ignore"):
                h = np.maximum(0.0, Xn @ self._w1 + self._b1)
                pred = h @ self._w2 + self._b2
                error = pred - yn
                grad_pred = np.clip(2.0 * error / len(Xn), -self.grad_clip, self.grad_clip)
                grad_w2 = np.clip(h.T @ grad_pred, -self.grad_clip, self.grad_clip)
                grad_b2 = float(np.clip(grad_pred.sum(), -self.grad_clip, self.grad_clip))
                grad_h = np.outer(grad_pred, self._w2) * (h > 0.0)
                grad_w1 = np.clip(Xn.T @ grad_h, -self.grad_clip, self.grad_clip)
                grad_b1 = np.clip(grad_h.sum(axis=0), -self.grad_clip, self.grad_clip)
                self._w2 -= self.learning_rate * grad_w2
                self._b2 -= self.learning_rate * grad_b2
                self._w1 -= self.learning_rate * grad_w1
                self._b1 -= self.learning_rate * grad_b1
            if not np.isfinite(self._w1).all() or not np.isfinite(self._w2).all():
                raise RuntimeError("lap-time map training diverged")

        h = np.maximum(0.0, Xn @ self._w1 + self._b1)
        pred = h @ self._w2 + self._b2
        residual = (pred - yn) * self._y_std
        self.train_rmse_s = float(np.sqrt(np.mean(residual**2)))
        self.n_train = len(samples)
        return self

    @property
    def domain(self):
        """Fitted feature range, as ``(min, max)`` arrays."""
        if self._x_min is None or self._x_max is None:
            raise RuntimeError("map is not fitted")
        return self._x_min.copy(), self._x_max.copy()

    def in_domain(self, deploy_w: float, mass_kg: float, soc0: float) -> bool:
        x = np.array([deploy_w, mass_kg, soc0])
        return bool(np.all(x >= self._x_min) and np.all(x <= self._x_max))

    def predict(self, deploy_w: float, mass_kg: float, soc0: float) -> float:
        if self._w1 is None:
            raise RuntimeError("map is not fitted")
        x = np.array([deploy_w, mass_kg, soc0])
        if not self.in_domain(deploy_w, mass_kg, soc0):
            raise ValueError("query outside the fitted range")
        xn = (x - self._x_mean) / self._x_std
        h = np.maximum(0.0, xn @ self._w1 + self._b1)
        return float((h @ self._w2 + self._b2) * self._y_std + self._y_mean)

    @property
    def n_parameters(self) -> int:
        if self._w1 is None:
            return 0
        return int(self._w1.size + self._b1.size + self._w2.size + 1)
