"""Generative plant: battery, track and longitudinal dynamics."""

from .battery import (
    TerminalPowerResult,
    chemical_energy_j,
    integrate as integrate_battery,
    max_transferable_power_w,
    open_circuit_voltage,
    resistance,
    soc_for_chemical_energy_j,
    solve_terminal_power,
    usable_energy_j,
)
from .plant import Plant, PlantStep, initial_state
from .track import TrackReference, build_track, synthetic_circuit
from .geometry import (
    Footprint,
    PassMonitor,
    PassOutcome,
    Pose,
    TrackPath,
    footprint_corners,
    footprint_within_track,
    rectangles_overlap,
)
from .tyres import (
    Compound,
    CompoundParams,
    TyreParams,
    TyreSetState,
    compounded_grip_multiplier,
    default_tyre_params,
    fresh_set,
    grip_multiplier,
    heat_input_w,
    integrate as integrate_tyres,
    reset_for_new_set,
    utilisation_stress,
)

__all__ = [
    "TerminalPowerResult",
    "chemical_energy_j",
    "integrate_battery",
    "max_transferable_power_w",
    "open_circuit_voltage",
    "resistance",
    "soc_for_chemical_energy_j",
    "solve_terminal_power",
    "usable_energy_j",
    "Plant",
    "PlantStep",
    "initial_state",
    "TrackReference",
    "build_track",
    "synthetic_circuit",
    "Footprint",
    "PassMonitor",
    "PassOutcome",
    "Pose",
    "TrackPath",
    "footprint_corners",
    "footprint_within_track",
    "rectangles_overlap",
    "Compound",
    "CompoundParams",
    "TyreParams",
    "TyreSetState",
    "compounded_grip_multiplier",
    "default_tyre_params",
    "fresh_set",
    "grip_multiplier",
    "heat_input_w",
    "integrate_tyres",
    "reset_for_new_set",
    "utilisation_stress",
]
